structname: Mock{{.InterfaceName}}
dir: "{{.InterfaceDir}}/mocks"
filename: mock_{{.InterfaceName}}.go
pkgname: mocks
packages:
  github.com/bitrise-steplib/bitrise-step-activate-react-native-features/step:
    interfaces:
      Command:
      InputParser:
      Logger:
