// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInputParser creates a new instance of MockInputParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInputParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInputParser {
	mock := &MockInputParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInputParser is an autogenerated mock type for the InputParser type
type MockInputParser struct {
	mock.Mock
}

type MockInputParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInputParser) EXPECT() *MockInputParser_Expecter {
	return &MockInputParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockInputParser
func (_mock *MockInputParser) Parse(conf any) error {
	ret := _mock.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(conf)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInputParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockInputParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - conf any
func (_e *MockInputParser_Expecter) Parse(conf interface{}) *MockInputParser_Parse_Call {
	return &MockInputParser_Parse_Call{Call: _e.mock.On("Parse", conf)}
}

func (_c *MockInputParser_Parse_Call) Run(run func(conf any)) *MockInputParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInputParser_Parse_Call) Return(err error) *MockInputParser_Parse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInputParser_Parse_Call) RunAndReturn(run func(conf any) error) *MockInputParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
