// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debugf provides a mock function for the type MockLogger
func (_mock *MockLogger) Debugf(format string, v ...any) {
	if len(v) > 0 {
		_mock.Called(format, v)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - v ...any
func (_e *MockLogger_Expecter) Debugf(format interface{}, v ...interface{}) *MockLogger_Debugf_Call {
	return &MockLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, v...)...)}
}

func (_c *MockLogger_Debugf_Call) Run(run func(format string, v ...any)) *MockLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debugf_Call) Return() *MockLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugf_Call) RunAndReturn(run func(format string, v ...any)) *MockLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// EnableDebugLog provides a mock function for the type MockLogger
func (_mock *MockLogger) EnableDebugLog(enable bool) {
	_mock.Called(enable)
	return
}

// MockLogger_EnableDebugLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDebugLog'
type MockLogger_EnableDebugLog_Call struct {
	*mock.Call
}

// EnableDebugLog is a helper method to define mock.On call
//   - enable bool
func (_e *MockLogger_Expecter) EnableDebugLog(enable interface{}) *MockLogger_EnableDebugLog_Call {
	return &MockLogger_EnableDebugLog_Call{Call: _e.mock.On("EnableDebugLog", enable)}
}

func (_c *MockLogger_EnableDebugLog_Call) Run(run func(enable bool)) *MockLogger_EnableDebugLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_EnableDebugLog_Call) Return() *MockLogger_EnableDebugLog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_EnableDebugLog_Call) RunAndReturn(run func(enable bool)) *MockLogger_EnableDebugLog_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function for the type MockLogger
func (_mock *MockLogger) Infof(format string, v ...any) {
	if len(v) > 0 {
		_mock.Called(format, v)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - v ...any
func (_e *MockLogger_Expecter) Infof(format interface{}, v ...interface{}) *MockLogger_Infof_Call {
	return &MockLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, v...)...)}
}

func (_c *MockLogger_Infof_Call) Run(run func(format string, v ...any)) *MockLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Infof_Call) Return() *MockLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infof_Call) RunAndReturn(run func(format string, v ...any)) *MockLogger_Infof_Call {
	_c.Run(run)
	return _c
}

// Println provides a mock function for the type MockLogger
func (_mock *MockLogger) Println() {
	_mock.Called()
	return
}

// MockLogger_Println_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Println'
type MockLogger_Println_Call struct {
	*mock.Call
}

// Println is a helper method to define mock.On call
func (_e *MockLogger_Expecter) Println() *MockLogger_Println_Call {
	return &MockLogger_Println_Call{Call: _e.mock.On("Println")}
}

func (_c *MockLogger_Println_Call) Run(run func()) *MockLogger_Println_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_Println_Call) Return() *MockLogger_Println_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Println_Call) RunAndReturn(run func()) *MockLogger_Println_Call {
	_c.Run(run)
	return _c
}

// Warnf provides a mock function for the type MockLogger
func (_mock *MockLogger) Warnf(format string, v ...any) {
	if len(v) > 0 {
		_mock.Called(format, v)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Warnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnf'
type MockLogger_Warnf_Call struct {
	*mock.Call
}

// Warnf is a helper method to define mock.On call
//   - format string
//   - v ...any
func (_e *MockLogger_Expecter) Warnf(format interface{}, v ...interface{}) *MockLogger_Warnf_Call {
	return &MockLogger_Warnf_Call{Call: _e.mock.On("Warnf",
		append([]interface{}{format}, v...)...)}
}

func (_c *MockLogger_Warnf_Call) Run(run func(format string, v ...any)) *MockLogger_Warnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warnf_Call) Return() *MockLogger_Warnf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warnf_Call) RunAndReturn(run func(format string, v ...any)) *MockLogger_Warnf_Call {
	_c.Run(run)
	return _c
}
