// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommand creates a new instance of MockCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommand {
	mock := &MockCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommand is an autogenerated mock type for the Command type
type MockCommand struct {
	mock.Mock
}

type MockCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommand) EXPECT() *MockCommand_Expecter {
	return &MockCommand_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCommand
func (_mock *MockCommand) Execute() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommand_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommand_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Execute() *MockCommand_Execute_Call {
	return &MockCommand_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockCommand_Execute_Call) Run(run func()) *MockCommand_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Execute_Call) Return(err error) *MockCommand_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommand_Execute_Call) RunAndReturn(run func() error) *MockCommand_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// SetArgs provides a mock function for the type MockCommand
func (_mock *MockCommand) SetArgs(a []string) {
	_mock.Called(a)
	return
}

// MockCommand_SetArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArgs'
type MockCommand_SetArgs_Call struct {
	*mock.Call
}

// SetArgs is a helper method to define mock.On call
//   - a []string
func (_e *MockCommand_Expecter) SetArgs(a interface{}) *MockCommand_SetArgs_Call {
	return &MockCommand_SetArgs_Call{Call: _e.mock.On("SetArgs", a)}
}

func (_c *MockCommand_SetArgs_Call) Run(run func(a []string)) *MockCommand_SetArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommand_SetArgs_Call) Return() *MockCommand_SetArgs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommand_SetArgs_Call) RunAndReturn(run func(a []string)) *MockCommand_SetArgs_Call {
	_c.Run(run)
	return _c
}
